# AUTO-GENERATED FILE. DO NOT EDIT.
MANIFEST = [   {   'description': 'Get Ui Status Handler',
        'method': 'GET',
        'name': 'get_ui_status_handler_ui_status_get',
        'params': [],
        'path': '/ui/status'},
    {   'description': 'Get Ui Audit Handler',
        'method': 'GET',
        'name': 'get_ui_audit_handler_ui_audit_get',
        'params': [   {   'in': 'query',
                          'name': 'limit',
                          'required': False,
                          'type': 'integer'}],
        'path': '/ui/audit'},
    {   'description': 'Get Ui Allowlist Handler',
        'method': 'GET',
        'name': 'get_ui_allowlist_handler_ui_allowlist_get',
        'params': [],
        'path': '/ui/allowlist'},
    {   'description': 'List Repos Handler',
        'method': 'GET',
        'name': 'list_repos_handler_ui_repos_get',
        'params': [],
        'path': '/ui/repos'},
    {   'description': 'Get Active Repo Handler',
        'method': 'GET',
        'name': 'get_active_repo_handler_ui_repos_active_get',
        'params': [],
        'path': '/ui/repos/active'},
    {   'description': 'Open Repo Handler',
        'method': 'POST',
        'name': 'open_repo_handler_ui_repos_open_post',
        'params': [   {   'in': 'query',
                          'name': 'path',
                          'required': True,
                          'type': 'string'}],
        'path': '/ui/repos/open'},
    {   'description': 'Select Repo Handler',
        'method': 'POST',
        'name': 'select_repo_handler_ui_repos_select_post',
        'params': [   {   'in': 'query',
                          'name': 'path',
                          'required': True,
                          'type': 'string'}],
        'path': '/ui/repos/select'},
    {   'description': 'Get Ui Graph Handler',
        'method': 'GET',
        'name': 'get_ui_graph_handler_ui_graph_get',
        'params': [],
        'path': '/ui/graph'},
    {   'description': 'Create Plan Handler',
        'method': 'POST',
        'name': 'create_plan_handler_ui_plan_create_post',
        'params': [],
        'path': '/ui/plan/create'},
    {   'description': 'Reject Draft Handler',
        'method': 'POST',
        'name': 'reject_draft_handler_ui_drafts__draft_id__reject_post',
        'params': [   {   'in': 'path',
                          'name': 'draft_id',
                          'required': True,
                          'type': 'string'}],
        'path': '/ui/drafts/{draft_id}/reject'},
    {   'description': 'List Ui Providers Bridge',
        'method': 'GET',
        'name': 'list_ui_providers_bridge_ui_providers_get',
        'params': [],
        'path': '/ui/providers'},
    {   'description': 'Add Ui Provider Bridge',
        'method': 'POST',
        'name': 'add_ui_provider_bridge_ui_providers_post',
        'params': [],
        'path': '/ui/providers'},
    {   'description': 'Remove Ui Provider Bridge',
        'method': 'DELETE',
        'name': 'remove_ui_provider_bridge_ui_providers__provider_id__delete',
        'params': [   {   'in': 'path',
                          'name': 'provider_id',
                          'required': True,
                          'type': 'string'}],
        'path': '/ui/providers/{provider_id}'},
    {   'description': 'Test Ui Provider Bridge',
        'method': 'POST',
        'name': 'test_ui_provider_bridge_ui_providers__provider_id__test_post',
        'params': [   {   'in': 'path',
                          'name': 'provider_id',
                          'required': True,
                          'type': 'string'}],
        'path': '/ui/providers/{provider_id}/test'},
    {   'description': 'List Ui Nodes Bridge',
        'method': 'GET',
        'name': 'list_ui_nodes_bridge_ui_nodes_get',
        'params': [],
        'path': '/ui/nodes'},
    {   'description': 'Compare Costs',
        'method': 'GET',
        'name': 'compare_costs_ui_cost_compare_get',
        'params': [   {   'in': 'query',
                          'name': 'model_a',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'query',
                          'name': 'model_b',
                          'required': True,
                          'type': 'string'}],
        'path': '/ui/cost/compare'},
    {   'description': 'Get Security Events Handler',
        'method': 'GET',
        'name': 'get_security_events_handler_ui_security_events_get',
        'params': [],
        'path': '/ui/security/events'},
    {   'description': 'Resolve Security Handler',
        'method': 'POST',
        'name': 'resolve_security_handler_ui_security_resolve_post',
        'params': [   {   'in': 'query',
                          'name': 'action',
                          'required': False,
                          'type': 'string'}],
        'path': '/ui/security/resolve'},
    {   'description': 'Get Service Status Handler',
        'method': 'GET',
        'name': 'get_service_status_handler_ui_service_status_get',
        'params': [],
        'path': '/ui/service/status'},
    {   'description': 'Restart Service Handler',
        'method': 'POST',
        'name': 'restart_service_handler_ui_service_restart_post',
        'params': [],
        'path': '/ui/service/restart'},
    {   'description': 'Stop Service Handler',
        'method': 'POST',
        'name': 'stop_service_handler_ui_service_stop_post',
        'params': [],
        'path': '/ui/service/stop'},
    {   'description': 'Vitaminize Repo Handler',
        'method': 'POST',
        'name': 'vitaminize_repo_handler_ui_repos_vitaminize_post',
        'params': [   {   'in': 'query',
                          'name': 'path',
                          'required': True,
                          'type': 'string'}],
        'path': '/ui/repos/vitaminize'},
    {   'description': 'Get Plan',
        'method': 'GET',
        'name': 'get_plan_ops_plan_get',
        'params': [],
        'path': '/ops/plan'},
    {   'description': 'Set Plan',
        'method': 'PUT',
        'name': 'set_plan_ops_plan_put',
        'params': [   {   'in': 'body',
                          'name': 'id',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'title',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'workspace',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'created',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'objective',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'tasks',
                          'required': True,
                          'type': 'array'},
                      {   'in': 'body',
                          'name': 'constraints',
                          'required': False,
                          'type': 'array'}],
        'path': '/ops/plan'},
    {   'description': 'List Drafts',
        'method': 'GET',
        'name': 'list_drafts_ops_drafts_get',
        'params': [],
        'path': '/ops/drafts'},
    {   'description': 'Create Draft',
        'method': 'POST',
        'name': 'create_draft_ops_drafts_post',
        'params': [   {   'in': 'body',
                          'name': 'prompt',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'context',
                          'required': False,
                          'type': 'object'}],
        'path': '/ops/drafts'},
    {   'description': 'Get Draft',
        'method': 'GET',
        'name': 'get_draft_ops_drafts__draft_id__get',
        'params': [   {   'in': 'path',
                          'name': 'draft_id',
                          'required': True,
                          'type': 'string'}],
        'path': '/ops/drafts/{draft_id}'},
    {   'description': 'Update Draft',
        'method': 'PUT',
        'name': 'update_draft_ops_drafts__draft_id__put',
        'params': [   {   'in': 'path',
                          'name': 'draft_id',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'prompt',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'content',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'context',
                          'required': False,
                          'type': 'string'}],
        'path': '/ops/drafts/{draft_id}'},
    {   'description': 'Reject Draft',
        'method': 'POST',
        'name': 'reject_draft_ops_drafts__draft_id__reject_post',
        'params': [   {   'in': 'path',
                          'name': 'draft_id',
                          'required': True,
                          'type': 'string'}],
        'path': '/ops/drafts/{draft_id}/reject'},
    {   'description': 'Generate Draft',
        'method': 'POST',
        'name': 'generate_draft_ops_generate_post',
        'params': [   {   'in': 'query',
                          'name': 'prompt',
                          'required': True,
                          'type': 'string'}],
        'path': '/ops/generate'},
    {   'description': 'Approve Draft',
        'method': 'POST',
        'name': 'approve_draft_ops_drafts__draft_id__approve_post',
        'params': [   {   'in': 'path',
                          'name': 'draft_id',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'query',
                          'name': 'auto_run',
                          'required': False,
                          'type': 'string'}],
        'path': '/ops/drafts/{draft_id}/approve'},
    {   'description': 'List Approved',
        'method': 'GET',
        'name': 'list_approved_ops_approved_get',
        'params': [],
        'path': '/ops/approved'},
    {   'description': 'Get Approved',
        'method': 'GET',
        'name': 'get_approved_ops_approved__approved_id__get',
        'params': [   {   'in': 'path',
                          'name': 'approved_id',
                          'required': True,
                          'type': 'string'}],
        'path': '/ops/approved/{approved_id}'},
    {   'description': 'List Runs',
        'method': 'GET',
        'name': 'list_runs_ops_runs_get',
        'params': [],
        'path': '/ops/runs'},
    {   'description': 'Create Run',
        'method': 'POST',
        'name': 'create_run_ops_runs_post',
        'params': [   {   'in': 'body',
                          'name': 'approved_id',
                          'required': True,
                          'type': 'string'}],
        'path': '/ops/runs'},
    {   'description': 'Get Run',
        'method': 'GET',
        'name': 'get_run_ops_runs__run_id__get',
        'params': [   {   'in': 'path',
                          'name': 'run_id',
                          'required': True,
                          'type': 'string'}],
        'path': '/ops/runs/{run_id}'},
    {   'description': 'Cancel Run',
        'method': 'POST',
        'name': 'cancel_run_ops_runs__run_id__cancel_post',
        'params': [   {   'in': 'path',
                          'name': 'run_id',
                          'required': True,
                          'type': 'string'}],
        'path': '/ops/runs/{run_id}/cancel'},
    {   'description': 'Execute Workflow',
        'method': 'POST',
        'name': 'execute_workflow_ops_workflows_execute_post',
        'params': [   {   'in': 'body',
                          'name': 'workflow',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'initial_state',
                          'required': False,
                          'type': 'object'},
                      {   'in': 'body',
                          'name': 'persist_checkpoints',
                          'required': False,
                          'type': 'boolean'},
                      {   'in': 'body',
                          'name': 'workflow_timeout_seconds',
                          'required': False,
                          'type': 'string'}],
        'path': '/ops/workflows/execute'},
    {   'description': 'List Workflow Checkpoints',
        'method': 'GET',
        'name': 'list_workflow_checkpoints_ops_workflows__workflow_id__checkpoin',
        'params': [   {   'in': 'path',
                          'name': 'workflow_id',
                          'required': True,
                          'type': 'string'}],
        'path': '/ops/workflows/{workflow_id}/checkpoints'},
    {   'description': 'Resume Workflow',
        'method': 'POST',
        'name': 'resume_workflow_ops_workflows__workflow_id__resume_post',
        'params': [   {   'in': 'path',
                          'name': 'workflow_id',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'query',
                          'name': 'from_checkpoint',
                          'required': False,
                          'type': 'integer'}],
        'path': '/ops/workflows/{workflow_id}/resume'},
    {   'description': 'Evals Run',
        'method': 'POST',
        'name': 'evals_run_ops_evals_run_post',
        'params': [   {   'in': 'query',
                          'name': 'fail_on_gate',
                          'required': False,
                          'type': 'boolean'},
                      {   'in': 'body',
                          'name': 'workflow',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'dataset',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'judge',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'gate',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'case_limit',
                          'required': False,
                          'type': 'string'}],
        'path': '/ops/evals/run'},
    {   'description': 'List Eval Runs',
        'method': 'GET',
        'name': 'list_eval_runs_ops_evals_runs_get',
        'params': [   {   'in': 'query',
                          'name': 'workflow_id',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'query',
                          'name': 'limit',
                          'required': False,
                          'type': 'integer'}],
        'path': '/ops/evals/runs'},
    {   'description': 'Get Eval Run',
        'method': 'GET',
        'name': 'get_eval_run_ops_evals_runs__run_id__get',
        'params': [   {   'in': 'path',
                          'name': 'run_id',
                          'required': True,
                          'type': 'integer'}],
        'path': '/ops/evals/runs/{run_id}'},
    {   'description': 'Create Eval Dataset',
        'method': 'POST',
        'name': 'create_eval_dataset_ops_evals_datasets_post',
        'params': [   {   'in': 'query',
                          'name': 'version_tag',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'workflow_id',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'name',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'description',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'cases',
                          'required': False,
                          'type': 'array'}],
        'path': '/ops/evals/datasets'},
    {   'description': 'List Eval Datasets',
        'method': 'GET',
        'name': 'list_eval_datasets_ops_evals_datasets_get',
        'params': [   {   'in': 'query',
                          'name': 'workflow_id',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'query',
                          'name': 'limit',
                          'required': False,
                          'type': 'integer'}],
        'path': '/ops/evals/datasets'},
    {   'description': 'Get Eval Dataset',
        'method': 'GET',
        'name': 'get_eval_dataset_ops_evals_datasets__dataset_id__get',
        'params': [   {   'in': 'path',
                          'name': 'dataset_id',
                          'required': True,
                          'type': 'integer'}],
        'path': '/ops/evals/datasets/{dataset_id}'},
    {   'description': 'Trust Query',
        'method': 'POST',
        'name': 'trust_query_ops_trust_query_post',
        'params': [],
        'path': '/ops/trust/query'},
    {   'description': 'Trust Dashboard',
        'method': 'GET',
        'name': 'trust_dashboard_ops_trust_dashboard_get',
        'params': [   {   'in': 'query',
                          'name': 'limit',
                          'required': False,
                          'type': 'integer'}],
        'path': '/ops/trust/dashboard'},
    {   'description': 'Trust Suggestions',
        'method': 'GET',
        'name': 'trust_suggestions_ops_trust_suggestions_get',
        'params': [   {   'in': 'query',
                          'name': 'limit',
                          'required': False,
                          'type': 'integer'}],
        'path': '/ops/trust/suggestions'},
    {   'description': 'Get Circuit Breaker Config',
        'method': 'GET',
        'name': 'get_circuit_breaker_config_ops_trust_circuit_breaker__dimension',
        'params': [   {   'in': 'path',
                          'name': 'dimension_key',
                          'required': True,
                          'type': 'string'}],
        'path': '/ops/trust/circuit-breaker/{dimension_key}'},
    {   'description': 'Set Circuit Breaker Config',
        'method': 'PUT',
        'name': 'set_circuit_breaker_config_ops_trust_circuit_breaker__dimension',
        'params': [   {   'in': 'path',
                          'name': 'dimension_key',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'window',
                          'required': False,
                          'type': 'integer'},
                      {   'in': 'body',
                          'name': 'failure_threshold',
                          'required': False,
                          'type': 'integer'},
                      {   'in': 'body',
                          'name': 'recovery_probes',
                          'required': False,
                          'type': 'integer'},
                      {   'in': 'body',
                          'name': 'cooldown_seconds',
                          'required': False,
                          'type': 'integer'}],
        'path': '/ops/trust/circuit-breaker/{dimension_key}'},
    {   'description': 'Trust Reset',
        'method': 'POST',
        'name': 'trust_reset_ops_trust_reset_post',
        'params': [],
        'path': '/ops/trust/reset'},
    {   'description': 'Get Provider',
        'method': 'GET',
        'name': 'get_provider_ops_provider_get',
        'params': [],
        'path': '/ops/provider'},
    {   'description': 'Set Provider',
        'method': 'PUT',
        'name': 'set_provider_ops_provider_put',
        'params': [   {   'in': 'body',
                          'name': 'schema_version',
                          'required': False,
                          'type': 'integer'},
                      {   'in': 'body',
                          'name': 'active',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'providers',
                          'required': True,
                          'type': 'object'},
                      {   'in': 'body',
                          'name': 'mcp_servers',
                          'required': False,
                          'type': 'object'},
                      {   'in': 'body',
                          'name': 'provider_type',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'model_id',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'auth_mode',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'auth_ref',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'last_validated_at',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'effective_state',
                          'required': False,
                          'type': 'object'},
                      {   'in': 'body',
                          'name': 'capabilities_snapshot',
                          'required': False,
                          'type': 'object'}],
        'path': '/ops/provider'},
    {   'description': 'Get Provider Capabilities',
        'method': 'GET',
        'name': 'get_provider_capabilities_ops_provider_capabilities_get',
        'params': [],
        'path': '/ops/provider/capabilities'},
    {   'description': 'List Connectors',
        'method': 'GET',
        'name': 'list_connectors_ops_connectors_get',
        'params': [],
        'path': '/ops/connectors'},
    {   'description': 'Connector Health',
        'method': 'GET',
        'name': 'connector_health_ops_connectors__connector_id__health_get',
        'params': [   {   'in': 'path',
                          'name': 'connector_id',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'query',
                          'name': 'provider_id',
                          'required': False,
                          'type': 'string'}],
        'path': '/ops/connectors/{connector_id}/health'},
    {   'description': 'Get Provider Models Catalog',
        'method': 'GET',
        'name': 'get_provider_models_catalog_ops_connectors__provider_type__mode',
        'params': [   {   'in': 'path',
                          'name': 'provider_type',
                          'required': True,
                          'type': 'string'}],
        'path': '/ops/connectors/{provider_type}/models'},
    {   'description': 'Install Provider Model',
        'method': 'POST',
        'name': 'install_provider_model_ops_connectors__provider_type__models_in',
        'params': [   {   'in': 'path',
                          'name': 'provider_type',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'model_id',
                          'required': True,
                          'type': 'string'}],
        'path': '/ops/connectors/{provider_type}/models/install'},
    {   'description': 'Get Provider Model Install Job',
        'method': 'GET',
        'name': 'get_provider_model_install_job_ops_connectors__provider_type__m',
        'params': [   {   'in': 'path',
                          'name': 'provider_type',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'path',
                          'name': 'job_id',
                          'required': True,
                          'type': 'string'}],
        'path': '/ops/connectors/{provider_type}/models/install/{job_id}'},
    {   'description': 'Validate Provider Credentials',
        'method': 'POST',
        'name': 'validate_provider_credentials_ops_connectors__provider_type__va',
        'params': [   {   'in': 'path',
                          'name': 'provider_type',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'api_key',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'base_url',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'org',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'account',
                          'required': False,
                          'type': 'string'}],
        'path': '/ops/connectors/{provider_type}/validate'},
    {   'description': 'Codex Device Login',
        'method': 'POST',
        'name': 'codex_device_login_ops_connectors_codex_login_post',
        'params': [],
        'path': '/ops/connectors/codex/login'},
    {   'description': 'Get Config',
        'method': 'GET',
        'name': 'get_config_ops_config_get',
        'params': [],
        'path': '/ops/config'},
    {   'description': 'Set Config',
        'method': 'PUT',
        'name': 'set_config_ops_config_put',
        'params': [   {   'in': 'body',
                          'name': 'default_auto_run',
                          'required': False,
                          'type': 'boolean'},
                      {   'in': 'body',
                          'name': 'draft_cleanup_ttl_days',
                          'required': False,
                          'type': 'integer'},
                      {   'in': 'body',
                          'name': 'max_concurrent_runs',
                          'required': False,
                          'type': 'integer'},
                      {   'in': 'body',
                          'name': 'operator_can_generate',
                          'required': False,
                          'type': 'boolean'},
                      {   'in': 'body',
                          'name': 'economy',
                          'required': False,
                          'type': 'string'}],
        'path': '/ops/config'},
    {   'description': 'List Mcp Servers',
        'method': 'GET',
        'name': 'list_mcp_servers_ops_config_mcp_get',
        'params': [],
        'path': '/ops/config/mcp'},
    {   'description': 'Sync Mcp Tools',
        'method': 'POST',
        'name': 'sync_mcp_tools_ops_config_mcp_sync_post',
        'params': [],
        'path': '/ops/config/mcp/sync'},
    {   'description': 'List Tool Registry',
        'method': 'GET',
        'name': 'list_tool_registry_ops_tool_registry_get',
        'params': [],
        'path': '/ops/tool-registry'},
    {   'description': 'Get Tool Registry Entry',
        'method': 'GET',
        'name': 'get_tool_registry_entry_ops_tool_registry__tool_name__get',
        'params': [   {   'in': 'path',
                          'name': 'tool_name',
                          'required': True,
                          'type': 'string'}],
        'path': '/ops/tool-registry/{tool_name}'},
    {   'description': 'Upsert Tool Registry Entry',
        'method': 'PUT',
        'name': 'upsert_tool_registry_entry_ops_tool_registry__tool_name__put',
        'params': [   {   'in': 'path',
                          'name': 'tool_name',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'name',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'description',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'inputs',
                          'required': False,
                          'type': 'object'},
                      {   'in': 'body',
                          'name': 'outputs',
                          'required': False,
                          'type': 'object'},
                      {   'in': 'body',
                          'name': 'risk',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'estimated_cost',
                          'required': False,
                          'type': 'number'},
                      {   'in': 'body',
                          'name': 'requires_hitl',
                          'required': False,
                          'type': 'boolean'},
                      {   'in': 'body',
                          'name': 'allowed_roles',
                          'required': False,
                          'type': 'array'},
                      {   'in': 'body',
                          'name': 'metadata',
                          'required': False,
                          'type': 'object'}],
        'path': '/ops/tool-registry/{tool_name}'},
    {   'description': 'Delete Tool Registry Entry',
        'method': 'DELETE',
        'name': 'delete_tool_registry_entry_ops_tool_registry__tool_name__delete',
        'params': [   {   'in': 'path',
                          'name': 'tool_name',
                          'required': True,
                          'type': 'string'}],
        'path': '/ops/tool-registry/{tool_name}'},
    {   'description': 'Get Policy Config',
        'method': 'GET',
        'name': 'get_policy_config_ops_policy_get',
        'params': [],
        'path': '/ops/policy'},
    {   'description': 'Set Policy Config',
        'method': 'PUT',
        'name': 'set_policy_config_ops_policy_put',
        'params': [   {   'in': 'body',
                          'name': 'rules',
                          'required': False,
                          'type': 'array'}],
        'path': '/ops/policy'},
    {   'description': 'Policy Decide',
        'method': 'POST',
        'name': 'policy_decide_ops_policy_decide_post',
        'params': [],
        'path': '/ops/policy/decide'},
    {   'description': 'Model Recommend',
        'method': 'POST',
        'name': 'model_recommend_ops_model_recommend_post',
        'params': [],
        'path': '/ops/model/recommend'},
    {   'description': 'Observability Metrics',
        'method': 'GET',
        'name': 'observability_metrics_ops_observability_metrics_get',
        'params': [],
        'path': '/ops/observability/metrics'},
    {   'description': 'Observability Traces',
        'method': 'GET',
        'name': 'observability_traces_ops_observability_traces_get',
        'params': [   {   'in': 'query',
                          'name': 'limit',
                          'required': False,
                          'type': 'integer'}],
        'path': '/ops/observability/traces'},
    {   'description': 'Observability Trace Detail',
        'method': 'GET',
        'name': 'observability_trace_detail_ops_observability_traces__trace_id__',
        'params': [   {   'in': 'path',
                          'name': 'trace_id',
                          'required': True,
                          'type': 'string'}],
        'path': '/ops/observability/traces/{trace_id}'},
    {   'description': 'Get Economy Config',
        'method': 'GET',
        'name': 'get_economy_config_ops_mastery_config_economy_get',
        'params': [],
        'path': '/ops/mastery/config/economy'},
    {   'description': 'Update Economy Config',
        'method': 'POST',
        'name': 'update_economy_config_ops_mastery_config_economy_post',
        'params': [   {   'in': 'body',
                          'name': 'autonomy_level',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'global_budget_usd',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'provider_budgets',
                          'required': False,
                          'type': 'array'},
                      {   'in': 'body',
                          'name': 'alert_thresholds',
                          'required': False,
                          'type': 'array'},
                      {   'in': 'body',
                          'name': 'cascade',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'eco_mode',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'allow_roi_routing',
                          'required': False,
                          'type': 'boolean'},
                      {   'in': 'body',
                          'name': 'model_floor',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'model_ceiling',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'cache_enabled',
                          'required': False,
                          'type': 'boolean'},
                      {   'in': 'body',
                          'name': 'cache_ttl_hours',
                          'required': False,
                          'type': 'integer'},
                      {   'in': 'body',
                          'name': 'show_cost_predictions',
                          'required': False,
                          'type': 'boolean'},
                      {   'in': 'body',
                          'name': 'provider_model_map',
                          'required': False,
                          'type': 'object'}],
        'path': '/ops/mastery/config/economy'},
    {   'description': 'Get Model Recommendations',
        'method': 'POST',
        'name': 'get_model_recommendations_ops_mastery_recommend_post',
        'params': [   {   'in': 'body',
                          'name': 'node',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'state',
                          'required': True,
                          'type': 'object'}],
        'path': '/ops/mastery/recommend'},
    {   'description': 'Get Mastery Status',
        'method': 'GET',
        'name': 'get_mastery_status_ops_mastery_status_get',
        'params': [],
        'path': '/ops/mastery/status'},
    {   'description': 'Get Mastery Recommendations',
        'method': 'GET',
        'name': 'get_mastery_recommendations_ops_mastery_recommendations_get',
        'params': [],
        'path': '/ops/mastery/recommendations'},
    {   'description': 'Predict Workflow Cost',
        'method': 'POST',
        'name': 'predict_workflow_cost_ops_mastery_predict_post',
        'params': [],
        'path': '/ops/mastery/predict'},
    {   'description': 'Get Mastery Analytics',
        'method': 'GET',
        'name': 'get_mastery_analytics_ops_mastery_analytics_get',
        'params': [   {   'in': 'query',
                          'name': 'days',
                          'required': False,
                          'type': 'integer'}],
        'path': '/ops/mastery/analytics'},
    {   'description': 'Get Budget Forecast',
        'method': 'GET',
        'name': 'get_budget_forecast_ops_mastery_forecast_get',
        'params': [],
        'path': '/ops/mastery/forecast'},
    {   'description': 'List Skills',
        'method': 'GET',
        'name': 'list_skills_ops_skills_get',
        'params': [],
        'path': '/ops/skills'},
    {   'description': 'Create Skill',
        'method': 'POST',
        'name': 'create_skill_ops_skills_post',
        'params': [   {   'in': 'body',
                          'name': 'name',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'description',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'icon',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'category',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'prompt_template',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'tags',
                          'required': False,
                          'type': 'array'},
                      {   'in': 'body',
                          'name': 'next_skill_id',
                          'required': False,
                          'type': 'string'}],
        'path': '/ops/skills'},
    {   'description': 'Get Skill',
        'method': 'GET',
        'name': 'get_skill_ops_skills__skill_id__get',
        'params': [   {   'in': 'path',
                          'name': 'skill_id',
                          'required': True,
                          'type': 'string'}],
        'path': '/ops/skills/{skill_id}'},
    {   'description': 'Update Skill',
        'method': 'PUT',
        'name': 'update_skill_ops_skills__skill_id__put',
        'params': [   {   'in': 'path',
                          'name': 'skill_id',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'name',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'description',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'icon',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'category',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'prompt_template',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'tags',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'next_skill_id',
                          'required': False,
                          'type': 'string'}],
        'path': '/ops/skills/{skill_id}'},
    {   'description': 'Delete Skill',
        'method': 'DELETE',
        'name': 'delete_skill_ops_skills__skill_id__delete',
        'params': [   {   'in': 'path',
                          'name': 'skill_id',
                          'required': True,
                          'type': 'string'}],
        'path': '/ops/skills/{skill_id}'},
    {   'description': 'Trigger Skill',
        'method': 'POST',
        'name': 'trigger_skill_ops_skills__skill_id__trigger_post',
        'params': [   {   'in': 'path',
                          'name': 'skill_id',
                          'required': True,
                          'type': 'string'}],
        'path': '/ops/skills/{skill_id}/trigger'},
    {   'description': 'List Plans',
        'method': 'GET',
        'name': 'list_plans_ops_custom_plans_get',
        'params': [],
        'path': '/ops/custom-plans'},
    {   'description': 'Create Plan',
        'method': 'POST',
        'name': 'create_plan_ops_custom_plans_post',
        'params': [   {   'in': 'body',
                          'name': 'name',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'description',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'nodes',
                          'required': False,
                          'type': 'array'},
                      {   'in': 'body',
                          'name': 'edges',
                          'required': False,
                          'type': 'array'}],
        'path': '/ops/custom-plans'},
    {   'description': 'Get Plan',
        'method': 'GET',
        'name': 'get_plan_ops_custom_plans__plan_id__get',
        'params': [   {   'in': 'path',
                          'name': 'plan_id',
                          'required': True,
                          'type': 'string'}],
        'path': '/ops/custom-plans/{plan_id}'},
    {   'description': 'Update Plan',
        'method': 'PUT',
        'name': 'update_plan_ops_custom_plans__plan_id__put',
        'params': [   {   'in': 'path',
                          'name': 'plan_id',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'name',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'description',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'nodes',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'body',
                          'name': 'edges',
                          'required': False,
                          'type': 'string'}],
        'path': '/ops/custom-plans/{plan_id}'},
    {   'description': 'Delete Plan',
        'method': 'DELETE',
        'name': 'delete_plan_ops_custom_plans__plan_id__delete',
        'params': [   {   'in': 'path',
                          'name': 'plan_id',
                          'required': True,
                          'type': 'string'}],
        'path': '/ops/custom-plans/{plan_id}'},
    {   'description': 'Execute Plan',
        'method': 'POST',
        'name': 'execute_plan_ops_custom_plans__plan_id__execute_post',
        'params': [   {   'in': 'path',
                          'name': 'plan_id',
                          'required': True,
                          'type': 'string'}],
        'path': '/ops/custom-plans/{plan_id}/execute'},
    {   'description': 'List Threads',
        'method': 'GET',
        'name': 'list_threads_ops_threads_get',
        'params': [   {   'in': 'query',
                          'name': 'workspace_root',
                          'required': False,
                          'type': 'string'}],
        'path': '/ops/threads'},
    {   'description': 'Create Thread',
        'method': 'POST',
        'name': 'create_thread_ops_threads_post',
        'params': [   {   'in': 'query',
                          'name': 'workspace_root',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'query',
                          'name': 'title',
                          'required': False,
                          'type': 'string'}],
        'path': '/ops/threads'},
    {   'description': 'Get Thread',
        'method': 'GET',
        'name': 'get_thread_ops_threads__thread_id__get',
        'params': [   {   'in': 'path',
                          'name': 'thread_id',
                          'required': True,
                          'type': 'string'}],
        'path': '/ops/threads/{thread_id}'},
    {   'description': 'Add Turn',
        'method': 'POST',
        'name': 'add_turn_ops_threads__thread_id__turns_post',
        'params': [   {   'in': 'path',
                          'name': 'thread_id',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'query',
                          'name': 'agent_id',
                          'required': True,
                          'type': 'string'}],
        'path': '/ops/threads/{thread_id}/turns'},
    {   'description': 'Add Item',
        'method': 'POST',
        'name': 'add_item_ops_threads__thread_id__turns__turn_id__items_post',
        'params': [   {   'in': 'path',
                          'name': 'thread_id',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'path',
                          'name': 'turn_id',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'query',
                          'name': 'type',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'query',
                          'name': 'content',
                          'required': False,
                          'type': 'string'}],
        'path': '/ops/threads/{thread_id}/turns/{turn_id}/items'},
    {   'description': 'Update Item',
        'method': 'PATCH',
        'name': 'update_item_ops_threads__thread_id__turns__turn_id__items__item',
        'params': [   {   'in': 'path',
                          'name': 'thread_id',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'path',
                          'name': 'turn_id',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'path',
                          'name': 'item_id',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'query',
                          'name': 'delta',
                          'required': False,
                          'type': 'string'},
                      {   'in': 'query',
                          'name': 'status',
                          'required': False,
                          'type': 'string'}],
        'path': '/ops/threads/{thread_id}/turns/{turn_id}/items/{item_id}'},
    {   'description': 'Fork Thread',
        'method': 'POST',
        'name': 'fork_thread_ops_threads__thread_id__fork_post',
        'params': [   {   'in': 'path',
                          'name': 'thread_id',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'query',
                          'name': 'turn_id',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'query',
                          'name': 'title',
                          'required': False,
                          'type': 'string'}],
        'path': '/ops/threads/{thread_id}/fork'},
    {   'description': 'Post Message',
        'method': 'POST',
        'name': 'post_message_ops_threads__thread_id__messages_post',
        'params': [   {   'in': 'path',
                          'name': 'thread_id',
                          'required': True,
                          'type': 'string'},
                      {   'in': 'query',
                          'name': 'content',
                          'required': True,
                          'type': 'string'}],
        'path': '/ops/threads/{thread_id}/messages'},
    {   'description': 'Get Filtered Openapi',
        'method': 'GET',
        'name': 'get_filtered_openapi_ops_openapi_json_get',
        'params': [],
        'path': '/ops/openapi.json'},
    {   'description': 'Ops Event Stream',
        'method': 'GET',
        'name': 'ops_event_stream_ops_stream_get',
        'params': [],
        'path': '/ops/stream'}]
