from __future__ import annotations


# Canonical set of provider types served via OpenAI-compatible chat completions adapter.
OPENAI_COMPAT_ADAPTER_TYPES = {
    "custom_openai_compatible",
    "ollama_local",
    "sglang",
    "lm_studio",
    "openai",
    "codex",
    "groq",
    "openrouter",
    "anthropic",
    "claude",
    "google",
    "mistral",
    "cohere",
    "deepseek",
    "qwen",
    "moonshot",
    "zai",
    "minimax",
    "baidu",
    "tencent",
    "bytedance",
    "iflytek",
    "01-ai",
    "together",
    "fireworks",
    "replicate",
    "huggingface",
    "azure-openai",
    "aws-bedrock",
    "vertex-ai",
    "vllm",
    "llama-cpp",
    "tgi",
}


# Canonical default API endpoints by provider type.
DEFAULT_BASE_URLS: dict[str, str] = {
    "openai": "https://api.openai.com/v1",
    "codex": "https://api.openai.com/v1",
    "groq": "https://api.groq.com/openai/v1",
    "openrouter": "https://openrouter.ai/api/v1",
    "anthropic": "https://api.anthropic.com/v1",
    "claude": "https://api.anthropic.com/v1",
    "google": "https://generativelanguage.googleapis.com/v1beta/openai",
    "mistral": "https://api.mistral.ai/v1",
    "cohere": "https://api.cohere.ai/compatibility/v1",
    "deepseek": "https://api.deepseek.com/v1",
    "qwen": "https://dashscope.aliyuncs.com/compatible-mode/v1",
    "moonshot": "https://api.moonshot.cn/v1",
    "zai": "https://api.z.ai/api/paas/v4",
    "minimax": "https://api.minimax.chat/v1",
    "baidu": "https://qianfan.baidubce.com/v2",
    "tencent": "https://api.lkeap.cloud.tencent.com/v1",
    "bytedance": "https://ark.cn-beijing.volces.com/api/v3",
    "iflytek": "https://spark-api-open.xf-yun.com/v1",
    "01-ai": "https://api.lingyiwanwu.com/v1",
    "together": "https://api.together.xyz/v1",
    "fireworks": "https://api.fireworks.ai/inference/v1",
    "huggingface": "https://router.huggingface.co/v1",
    "sglang": "http://localhost:30000/v1",
    "lm_studio": "http://localhost:1234/v1",
}


# Provider types that should use remote /models discovery through OpenAI-compatible APIs.
# Intentionally excludes local runtimes (ollama_local/sglang/lm_studio) and providers
# with dedicated catalog handling paths.
OPENAI_COMPAT_CATALOG_TYPES = {
    "openai",
    "codex",
    "groq",
    "openrouter",
    "custom_openai_compatible",
    "deepseek",
    "qwen",
    "moonshot",
    "zai",
    "minimax",
    "baidu",
    "tencent",
    "bytedance",
    "iflytek",
    "01-ai",
    "together",
    "fireworks",
    "huggingface",
    "vllm",
    "llama-cpp",
    "tgi",
}


# Default base URLs to discover provider model catalogs.
# Empty values represent providers that require user-supplied endpoint configuration.
REMOTE_MODELS_BASE_URLS: dict[str, str] = {
    "openai": "https://api.openai.com/v1",
    "codex": "https://api.openai.com/v1",
    "groq": "https://api.groq.com/openai/v1",
    "openrouter": "https://openrouter.ai/api/v1",
    "anthropic": "https://api.anthropic.com/v1",
    "claude": "https://api.anthropic.com/v1",
    "google": "https://generativelanguage.googleapis.com/v1beta/openai",
    "mistral": "https://api.mistral.ai/v1",
    "cohere": "https://api.cohere.ai/compatibility/v1",
    "deepseek": "https://api.deepseek.com/v1",
    "qwen": "https://dashscope.aliyuncs.com/compatible-mode/v1",
    "moonshot": "https://api.moonshot.cn/v1",
    "zai": "https://api.z.ai/api/paas/v4",
    "minimax": "https://api.minimax.chat/v1",
    "baidu": "https://qianfan.baidubce.com/v2",
    "tencent": "https://api.lkeap.cloud.tencent.com/v1",
    "bytedance": "https://ark.cn-beijing.volces.com/api/v3",
    "iflytek": "https://spark-api-open.xf-yun.com/v1",
    "01-ai": "https://api.lingyiwanwu.com/v1",
    "together": "https://api.together.xyz/v1",
    "fireworks": "https://api.fireworks.ai/inference/v1",
    "huggingface": "https://router.huggingface.co/v1",
    "azure-openai": "",
    "aws-bedrock": "",
    "vertex-ai": "",
    "replicate": "",
    "custom_openai_compatible": "",
    "vllm": "",
    "llama-cpp": "",
    "tgi": "",
}
